// <auto-generated />
using System;
using GuitarApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GuitarApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GuitarAppDbContext))]
    partial class GuitarAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuitarApp.Domain.Gear.Amp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_amps");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_amps_slug");

                    b.ToTable("amps", null, t =>
                        {
                            t.HasCheckConstraint("ck_amps_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("GuitarApp.Domain.Gear.Effect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_effects");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_effects_kind");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_effects_slug");

                    b.ToTable("effects", null, t =>
                        {
                            t.HasCheckConstraint("ck_effects_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("GuitarApp.Domain.Gear.Preset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AmpId")
                        .HasColumnType("uuid")
                        .HasColumnName("amp_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_presets");

                    b.HasIndex("AmpId")
                        .HasDatabaseName("ix_presets_amp_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_presets_slug");

                    b.ToTable("presets", null, t =>
                        {
                            t.HasCheckConstraint("ck_presets_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("GuitarApp.Domain.Gear.PresetBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EffectId")
                        .HasColumnType("uuid")
                        .HasColumnName("effect_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("PresetId")
                        .HasColumnType("uuid")
                        .HasColumnName("preset_id");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_preset_blocks");

                    b.HasIndex("EffectId")
                        .HasDatabaseName("ix_preset_blocks_effect_id");

                    b.HasIndex("PresetId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_preset_blocks_preset_id_order");

                    b.ToTable("preset_blocks", (string)null);
                });

            modelBuilder.Entity("GuitarApp.Domain.Music.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_albums");

                    b.HasIndex("ArtistId", "Title")
                        .IsUnique()
                        .HasDatabaseName("ix_albums_artist_id_title");

                    b.ToTable("albums", null, t =>
                        {
                            t.HasCheckConstraint("ck_albums_year", "year IS NULL OR year BETWEEN 1900 AND 2100");
                        });
                });

            modelBuilder.Entity("GuitarApp.Domain.Music.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_artists");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_artists_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_artists_slug");

                    b.ToTable("artists", null, t =>
                        {
                            t.HasCheckConstraint("ck_artists_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("GuitarApp.Domain.Music.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<int?>("Bpm")
                        .HasColumnType("integer")
                        .HasColumnName("bpm");

                    b.Property<int?>("Capo")
                        .HasColumnType("integer")
                        .HasColumnName("capo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("genre");

                    b.Property<string>("Key")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("key");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("ThumbnailKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("thumbnail_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("TuningId")
                        .HasColumnType("uuid")
                        .HasColumnName("tuning_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_songs");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("ix_songs_album_id");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_songs_artist_id");

                    b.HasIndex("Difficulty")
                        .HasDatabaseName("ix_songs_difficulty");

                    b.HasIndex("Genre")
                        .HasDatabaseName("ix_songs_genre");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_songs_slug");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_songs_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("TuningId")
                        .HasDatabaseName("ix_songs_tuning_id");

                    b.ToTable("songs", null, t =>
                        {
                            t.HasCheckConstraint("ck_songs_bpm", "bpm IS NULL OR bpm BETWEEN 20 AND 400");

                            t.HasCheckConstraint("ck_songs_capo", "capo IS NULL OR capo BETWEEN 0 AND 12");

                            t.HasCheckConstraint("ck_songs_difficulty", "difficulty BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_songs_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("GuitarApp.Domain.Music.Tuning", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tunings");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tunings_name");

                    b.ToTable("tunings", (string)null);
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.Chord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("label");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("quality");

                    b.Property<string>("Root")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("root");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chords");

                    b.HasIndex("Root", "Quality")
                        .IsUnique()
                        .HasDatabaseName("ix_chords_root_quality");

                    b.ToTable("chords", (string)null);
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.ChordVoicing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BaseFret")
                        .HasColumnType("integer")
                        .HasColumnName("base_fret");

                    b.Property<Guid>("ChordId")
                        .HasColumnType("uuid")
                        .HasColumnName("chord_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<int[]>("Fingers")
                        .HasColumnType("integer[]")
                        .HasColumnName("fingers");

                    b.PrimitiveCollection<int[]>("Frets")
                        .HasColumnType("integer[]")
                        .HasColumnName("frets");

                    b.Property<string>("FretsSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frets_source");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preferred");

                    b.Property<string>("Label")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chord_voicings");

                    b.HasIndex("ChordId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_chord_voicings_chord_id_index");

                    b.ToTable("chord_voicings", null, t =>
                        {
                            t.HasCheckConstraint("ck_chord_voicings_fingers_len", "fingers IS NULL OR cardinality(fingers) = 6");

                            t.HasCheckConstraint("ck_chord_voicings_frets_len", "frets IS NULL OR cardinality(frets) = 6");

                            t.HasCheckConstraint("ck_chord_voicings_frets_source", "frets_source IS NULL OR (frets IS NOT NULL AND frets_source IN ('authored', 'chords-db'))");

                            t.HasCheckConstraint("ck_chord_voicings_index", "\"index\" >= 0");

                            t.HasCheckConstraint("ck_chord_voicings_known", "frets IS NOT NULL OR fingers IS NOT NULL");
                        });
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.MusicConcept", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("ShapesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("shapes_json");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_music_concepts");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_music_concepts_kind");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_music_concepts_slug");

                    b.ToTable("music_concepts", null, t =>
                        {
                            t.HasCheckConstraint("ck_music_concepts_kind", "kind IN ('chord', 'scale')");

                            t.HasCheckConstraint("ck_music_concepts_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.Scale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("family");

                    b.PrimitiveCollection<string[]>("IntervalPattern")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("interval_pattern");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scales");

                    b.HasIndex("Family")
                        .HasDatabaseName("ix_scales_family");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_scales_slug");

                    b.ToTable("scales", null, t =>
                        {
                            t.HasCheckConstraint("ck_scales_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.ScalePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("FretCount")
                        .HasColumnType("integer")
                        .HasColumnName("fret_count");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("label");

                    b.Property<Guid>("ScaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("scale_id");

                    b.Property<int>("StartFret")
                        .HasColumnType("integer")
                        .HasColumnName("start_fret");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scale_positions");

                    b.HasIndex("ScaleId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_scale_positions_scale_id_index");

                    b.ToTable("scale_positions", null, t =>
                        {
                            t.HasCheckConstraint("ck_scale_positions_fret_count", "fret_count BETWEEN 1 AND 24");

                            t.HasCheckConstraint("ck_scale_positions_start_fret", "start_fret BETWEEN 0 AND 24");
                        });
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.ScalePositionNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int?>("Finger")
                        .HasColumnType("integer")
                        .HasColumnName("finger");

                    b.Property<int>("Fret")
                        .HasColumnType("integer")
                        .HasColumnName("fret");

                    b.Property<string>("Interval")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("interval");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("boolean")
                        .HasColumnName("is_root");

                    b.Property<Guid>("ScalePositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("scale_position_id");

                    b.Property<int>("String")
                        .HasColumnType("integer")
                        .HasColumnName("string");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scale_position_notes");

                    b.HasIndex("ScalePositionId", "String", "Fret")
                        .IsUnique()
                        .HasDatabaseName("ix_scale_position_notes_scale_position_id_string_fret");

                    b.ToTable("scale_position_notes", null, t =>
                        {
                            t.HasCheckConstraint("ck_scale_position_notes_fret", "fret BETWEEN 0 AND 24");

                            t.HasCheckConstraint("ck_scale_position_notes_string", "string BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.Technique", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_techniques");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_techniques_slug");

                    b.ToTable("techniques", null, t =>
                        {
                            t.HasCheckConstraint("ck_techniques_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("GuitarApp.Domain.Gear.Preset", b =>
                {
                    b.HasOne("GuitarApp.Domain.Gear.Amp", null)
                        .WithMany()
                        .HasForeignKey("AmpId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_presets_amps_amp_id");
                });

            modelBuilder.Entity("GuitarApp.Domain.Gear.PresetBlock", b =>
                {
                    b.HasOne("GuitarApp.Domain.Gear.Effect", null)
                        .WithMany()
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_preset_blocks_effects_effect_id");

                    b.HasOne("GuitarApp.Domain.Gear.Preset", null)
                        .WithMany("Blocks")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preset_blocks_presets_preset_id");
                });

            modelBuilder.Entity("GuitarApp.Domain.Music.Album", b =>
                {
                    b.HasOne("GuitarApp.Domain.Music.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_albums_artists_artist_id");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("GuitarApp.Domain.Music.Song", b =>
                {
                    b.HasOne("GuitarApp.Domain.Music.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_songs_albums_album_id");

                    b.HasOne("GuitarApp.Domain.Music.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_songs_artists_artist_id");

                    b.HasOne("GuitarApp.Domain.Music.Tuning", "Tuning")
                        .WithMany()
                        .HasForeignKey("TuningId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_songs_tunings_tuning_id");

                    b.Navigation("Album");

                    b.Navigation("Artist");

                    b.Navigation("Tuning");
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.ChordVoicing", b =>
                {
                    b.HasOne("GuitarApp.Domain.Reference.Chord", null)
                        .WithMany("Voicings")
                        .HasForeignKey("ChordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chord_voicings_chords_chord_id");
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.ScalePosition", b =>
                {
                    b.HasOne("GuitarApp.Domain.Reference.Scale", null)
                        .WithMany("Positions")
                        .HasForeignKey("ScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scale_positions_scales_scale_id");
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.ScalePositionNote", b =>
                {
                    b.HasOne("GuitarApp.Domain.Reference.ScalePosition", null)
                        .WithMany("Notes")
                        .HasForeignKey("ScalePositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scale_position_notes_scale_positions_scale_position_id");
                });

            modelBuilder.Entity("GuitarApp.Domain.Gear.Preset", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("GuitarApp.Domain.Music.Artist", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.Chord", b =>
                {
                    b.Navigation("Voicings");
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.Scale", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("GuitarApp.Domain.Reference.ScalePosition", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
